version: '3.8'

services:
  openvpn:
    image: kylemanna/openvpn
    container: openvpn
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./openvpn-data:/etc/openvpn
    restart: unless-stopped
    environment:
      - PUSH_DNS=8.8.8.8 8.8.4.4
